export const MenuSections = {
    INICIO: 1,
    ADMINISTRADOR: 2,
    COMPRAS: 3,
    PEDIDOS: 4,
    CARTERA: 5,
    VENDEDORES: 6,
    INFORMES: 7,
    PORTAFOLIOS: 8,
    PRODUCTOS: 9,
    CATALOGOS: 10,
}

//PARA LA VALIDACION LOS PRIMEROS DIGITOS CORRESPONDER AL MENUSECTION QUE CORRESPONDER Y EL ULTIMO DIGITO UN INDICADOR DE EL NUMEOR DEL SUBMENU
export const SubMenuSections = {
    DEFAULT:0,
    CARGAR_CONTENEDOR: 31,
    LIQUIDAR: 32,
    CATALOGOS_PDF: 101,
    VER_CATALOGOS_PDF: 102,
}